# 欢迎使用 Jekyll!

# 基本站点设置
locale                   : "zh-CN"
title                    : "想些什么就写什么"
title_separator          : "-"
name                     : "我是小丑"
description              : "个人博客"
url                      : https://flowaiwzm.github.io
baseurl                  : ""
repository               : "flowaiwzm/flowaiwzm.github.io"

# 站点作者
author:
  avatar           : "profile.png"
  name             : "诗人我吃"
  bio              : "侧边栏的简短简介"
  location         : "地球"
  employer         : "红砖大学"
  email            : "2153146182@qq.com" 
  googlescholar    : "https://scholar.google.com/citations?user=PS_CX0AAAAAJ"
  pubmed           : "https://www.ncbi.nlm.nih.gov/pubmed/?term=john+snow"
  github           : "academicpages"
  bluesky          : "bsky.app"

# 站点设置
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled"
talkmap_link             : false
comments:
  provider               : false

# SEO 相关
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# 社交分享
twitter:
  username               : "your_twitter_username"
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 :

# 分析
analytics:
  provider               : false

# 读取文件
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# 转换
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown 处理
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# 集合
collections:
  posts:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/


defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# 输出
permalink: /:categories/:title/
timezone: America/Los_Angeles

# 插件
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# 压缩HTML
compress_html:
  clippings: all
  ignore:
    envs: development
